CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" int NOT NULL,
  "name" varchar(25) NOT NULL,
  "email" varchar(25) UNIQUE NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "description" varchar(25) NOT NULL,
  "teacher" int NOT NULL,
  "category" int NOT NULL,
  "level" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "url" varchar(50) NOT NULL,
  "course" int NOT NULL
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "rol" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

ALTER TABLE "course_video" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol") REFERENCES "rol" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("category") REFERENCES "category" ("id");

INSERT INTO rol (name) VALUES ('Student'), ('Teacher'),('Admin');

INSERT INTO users (name, email, password, age, rol) VALUES ('Enrique' ,'rchavezs@uni.pe', '12345', 24, 1), ('Carlos', 'carlos@gmail.com', '123456', 30 , 2);

INSERT INTO level (name) VALUES ('Basic') , ('Intermediate') , ('Avanced');

INSERT INTO category (name) VALUES ('Backend') , ('Frontend');

INSERT INTO course ( title  ,  description  ,  teacher , category , level) VALUES ('Django' , 'Framework de python' , 2 , 1 , 1) , ('React' , 'Libreria de Java Script' , 2 , 2 , 2);

INSERT INTO course_video (title , url , course) VALUES ('Views and Serializers' , 'https://django/serializers' , 1) , ('Redux' , 'https://react/redux' , 2);