CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" int NOT NULL,
  "name" varchar(25) NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "admin" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL
);

CREATE TABLE "student" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "categorie" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "description" varchar(100) NOT NULL,
  "level" int NOT NULL,
  "teacher" int NOT NULL,
  "categorie" int NOT NULL
);

CREATE TABLE "item_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int NOT NULL,
  "student" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(200) NOT NULL,
  "course" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role") REFERENCES "role" ("id");

ALTER TABLE "admin" ADD FOREIGN KEY ("users") REFERENCES "users" ("id");

ALTER TABLE "teacher" ADD FOREIGN KEY ("users") REFERENCES "users" ("id");

ALTER TABLE "student" ADD FOREIGN KEY ("users") REFERENCES "users" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("categorie") REFERENCES "categorie" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("teacher") REFERENCES "teacher" ("id");

ALTER TABLE "item_course" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");

ALTER TABLE "item_course" ADD FOREIGN KEY ("student") REFERENCES "student" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");


INSERT INTO role (name) VALUES ('Student'), ('Teacher'),('Admin');

INSERT INTO users (name, email, password, age, role) VALUES ('Enrique' ,'rchavezs@uni.pe', '12345', 24, 1), ('Carlos', 'carlos@gmail.com', '123456', 30 , 2), ('Isabel', 'isabel@gmail.com', '123456', 25, 3);

INSERT INTO admin (users) VALUES (3);

INSERT INTO teacher (users) VALUES (2);

INSERT INTO student (users) VALUES (1);

INSERT INTO level (name) VALUES ('Basic') , ('Intermediate') , ('Avanced');

INSERT INTO categorie (name) VALUES ('Backend') , ('Frontend');

INSERT INTO course ( title  ,  description  ,  teacher , categorie , level) VALUES ('Django' , 'Framework de python' , 1 , 1 , 1) , ('React' , 'Libreria de Java Script' , 1 , 2 , 2);

INSERT INTO item_course ( course  ,  student ) VALUES (1 , 1 ) , (2,1);

INSERT INTO course_video (title , url , course) VALUES ('Views and Serializers' , 'https://django/serializers' , 1) , ('Redux' , 'https://react/redux' , 2);